import { type Host } from "./types";

/**
 * Sources we monitor for SF AI events.
 *
 * Tier reflects priority for the CAIS Head of Delivery search:
 *   1 = highest archetype density (FDE / Staff Eng / failed founder)
 *   2 = strong adjacent communities
 *   3 = invite-only dinners and salons (often need warm intros)
 *   4 = hackathons (sourcing-rich but require a specific approach)
 *
 * baseScore (0-100) seeds the LLM scorer; LLM can override per event.
 * sourceType tells the scraper which adapter to use.
 */
export const HOSTS: Host[] = [
  // ───────────────────────── Tier 1 ─────────────────────────
  {
    slug: "latent-space",
    name: "Latent Space (swyx)",
    tier: 1,
    baseScore: 92,
    url: "https://lu.ma/ls",
    sourceType: "luma",
    notes: "Highest-density Tier 1. Includes AI Engineer World's Fair org.",
  },
  {
    slug: "ai-engineer",
    name: "AI Engineer Conferences",
    tier: 1,
    baseScore: 95,
    url: "https://www.ai.engineer/",
    sourceType: "web",
    notes: "World's Fair (June) + AI Engineer Summit (Feb). Apply to speak.",
  },
  {
    slug: "mlops-community",
    name: "MLOps Community SF",
    tier: 1,
    baseScore: 86,
    url: "https://lu.ma/mlops-community",
    sourceType: "luma",
    notes: "Demetrios Brinkmann. Production-focused = the scars.",
  },
  {
    slug: "anthropic-events",
    name: "Anthropic Developer Events",
    tier: 1,
    baseScore: 90,
    url: "https://www.anthropic.com/events",
    sourceType: "web",
    notes: "DevDays, partner events. SAs themselves are candidates.",
  },
  {
    slug: "openai-events",
    name: "OpenAI Developer Events",
    tier: 1,
    baseScore: 88,
    url: "https://openai.com/events",
    sourceType: "web",
    notes: "DevDay, hackathons. SAs are candidates.",
  },
  {
    slug: "langchain",
    name: "LangChain",
    tier: 1,
    baseScore: 78,
    url: "https://lu.ma/langchain",
    sourceType: "luma",
    notes: "Framework-specific = active builders. Skews junior; filter hard.",
  },
  {
    slug: "dspy",
    name: "DSPy Community",
    tier: 1,
    baseScore: 80,
    url: "https://lu.ma/dspy",
    sourceType: "luma",
    notes: "Stanford-adjacent, high-signal builders.",
  },

  // ───────────────────────── Tier 2 ─────────────────────────
  {
    slug: "agi-house",
    name: "AGI House SF",
    tier: 2,
    baseScore: 82,
    url: "https://lu.ma/agi-house",
    sourceType: "luma",
    notes: "Multiple hackathons/month. Solo builders = failed-founder density.",
  },
  {
    slug: "cerebral-valley",
    name: "Cerebral Valley",
    tier: 2,
    baseScore: 78,
    url: "https://lu.ma/cerebralvalley",
    sourceType: "luma",
    notes: "Demo nights, larger rooms (~200). Wider net.",
  },
  {
    slug: "south-park-commons",
    name: "South Park Commons (public events)",
    tier: 2,
    baseScore: 88,
    url: "https://lu.ma/southparkcommons-events",
    sourceType: "luma",
    notes: "'Between things' demographic. Public events only without sponsor.",
  },
  {
    slug: "ai-tinkerers",
    name: "AI Tinkerers SF",
    tier: 2,
    baseScore: 76,
    url: "https://sf.aitinkerers.org/",
    sourceType: "web",
    notes: "Monthly demos, free. 120k+ Bond AI overlap.",
  },
  {
    slug: "bond-ai",
    name: "Bond AI / GenAI SF",
    tier: 2,
    baseScore: 70,
    url: "https://lu.ma/genai-sf",
    sourceType: "luma",
    notes: "Largest aggregator. High frequency, lower archetype density.",
  },
  {
    slug: "shack15",
    name: "Shack15 (Ferry Building)",
    tier: 2,
    baseScore: 75,
    url: "https://lu.ma/shack15",
    sourceType: "luma",
    notes: "Tech/AI community space. Hosts many Tier 1 evening events.",
  },
  {
    slug: "ray-summit",
    name: "Ray Summit (Anyscale)",
    tier: 2,
    baseScore: 80,
    url: "https://www.anyscale.com/ray-summit",
    sourceType: "web",
    notes: "Annual conference (~Sept). Infra-savvy production practitioners.",
  },
  {
    slug: "ai-council",
    name: "AI Council Conference",
    tier: 2,
    baseScore: 78,
    url: "https://aicouncil.com/sf-2026",
    sourceType: "web",
    notes: "Multi-track SF conference, OpenAI/Anthropic/Databricks speakers.",
  },

  // ───────────────────────── Tier 3 ─────────────────────────
  // Invite-only — most don't surface publicly. We track host pages for any
  // public talks they do, then flag warm-intro paths.
  {
    slug: "hamel-husain",
    name: "Hamel Husain (operator dinners)",
    tier: 3,
    baseScore: 94,
    url: "https://hamel.dev/",
    sourceType: "web",
    notes: "Curates aggressively for the exact archetype. Warm intro required.",
  },
  {
    slug: "eugene-yan",
    name: "Eugene Yan (reading group/dinners)",
    tier: 3,
    baseScore: 88,
    url: "https://eugeneyan.com/",
    sourceType: "web",
    notes: "Production AI focus. Smaller rooms.",
  },
  {
    slug: "jason-liu",
    name: "Jason Liu (Instructor meetups)",
    tier: 3,
    baseScore: 84,
    url: "https://jxnl.co/",
    sourceType: "web",
    notes: "Structured outputs / production patterns crowd.",
  },
  {
    slug: "spc-private",
    name: "South Park Commons (member dinners)",
    tier: 3,
    baseScore: 90,
    url: "https://www.southparkcommons.com/events",
    sourceType: "web",
    notes: "Member-only. Need SPC sponsor for invite.",
  },
  {
    slug: "hf0",
    name: "HF0 (Hacker Fellowship Zero)",
    tier: 3,
    baseScore: 86,
    url: "https://www.hf0.com/",
    sourceType: "web",
    notes: "Fellow demo events. Failed-founder hunting ground.",
  },

  // ──────────────────────────────────────────────────────────
  // EXPANSION WAVE 1 + 2 — VC-hosted, accelerator, AI-native
  // firm communities, individual hosts, hackathons, aggregators.
  // ──────────────────────────────────────────────────────────

  // ───────── Tier 1: VC-hosted (failed-founder gold) ─────────
  {
    slug: "y-combinator",
    name: "Y Combinator events",
    tier: 1,
    baseScore: 92,
    url: "https://events.ycombinator.com/",
    sourceType: "web",
    notes: "Failed-founder archetype is heavily YC-alumni. Public events bring the 'between things' cohort.",
  },
  {
    slug: "yc-startup-school",
    name: "YC AI Startup School",
    tier: 1,
    baseScore: 90,
    url: "https://www.ycombinator.com/library",
    sourceType: "web",
    notes: "Periodic AI-focused YC sessions. Technical founder audience.",
  },
  {
    slug: "a16z",
    name: "a16z events (general AI)",
    tier: 1,
    baseScore: 90,
    url: "https://a16z.com/events/",
    sourceType: "web",
    notes: "Curated dinners/summits for AI founders and operators. Invite-only but leaks publicly.",
  },
  {
    slug: "a16z-speedrun",
    name: "a16z Speedrun events",
    tier: 1,
    baseScore: 88,
    url: "https://a16z.com/games/speedrun/",
    sourceType: "web",
    notes: "a16z's accelerator. Demo days surface technical co-founders.",
  },
  {
    slug: "sequoia",
    name: "Sequoia Capital events (AI Ascent, Arc, Summit)",
    tier: 1,
    baseScore: 90,
    url: "https://www.sequoiacap.com/events/",
    sourceType: "web",
    notes: "Annual AI Ascent + smaller dinners. Exec-level operators.",
  },
  {
    slug: "conviction",
    name: "Conviction (Sarah Guo)",
    tier: 1,
    baseScore: 90,
    url: "https://conviction.com/",
    sourceType: "web",
    notes: "AI-focused VC. Hosts intimate dinners with founders. Sarah Guo curates the room.",
  },
  {
    slug: "greylock",
    name: "Greylock Greymatter / AI events",
    tier: 1,
    baseScore: 84,
    url: "https://greylock.com/events/",
    sourceType: "web",
    notes: "AI-focused VC events. Senior practitioners + portfolio founders.",
  },

  // ───────── Tier 2: AI-native firm communities ─────────
  {
    slug: "founders-inc",
    name: "Founders Inc",
    tier: 2,
    baseScore: 84,
    url: "https://f.inc/",
    sourceType: "web",
    notes: "YC-alumni-heavy SF community. Demo nights, hackathons, founder dinners.",
  },
  {
    slug: "modal-labs",
    name: "Modal Labs events",
    tier: 2,
    baseScore: 86,
    url: "https://modal.com/blog",
    sourceType: "web",
    notes: "Target candidate firm. Their meetups bring out their staff (FDE/Staff Eng archetype).",
  },
  {
    slug: "together-ai",
    name: "Together AI events",
    tier: 2,
    baseScore: 84,
    url: "https://www.together.ai/blog",
    sourceType: "web",
    notes: "Infra company on the candidate target list. Hosts technical events.",
  },
  {
    slug: "replicate",
    name: "Replicate events",
    tier: 2,
    baseScore: 80,
    url: "https://replicate.com/events",
    sourceType: "web",
    notes: "Builder community around model deployment. Practitioners.",
  },
  {
    slug: "build-club",
    name: "Build Club",
    tier: 2,
    baseScore: 78,
    url: "https://www.buildclub.ai/",
    sourceType: "web",
    notes: "Hands-on AI builder community, weekly events.",
  },
  {
    slug: "buildspace",
    name: "Buildspace / Sage",
    tier: 2,
    baseScore: 80,
    url: "https://buildspace.so/",
    sourceType: "web",
    notes: "Solo builders, failed founders exploring next thing. Demo nights.",
  },
  {
    slug: "the-residency",
    name: "The Residency",
    tier: 2,
    baseScore: 82,
    url: "https://residency.so/",
    sourceType: "web",
    notes: "Founder house in SF — hosts dinners and demo nights. Failed-founder density.",
  },
  {
    slug: "pinecone",
    name: "Pinecone events",
    tier: 2,
    baseScore: 76,
    url: "https://www.pinecone.io/events/",
    sourceType: "web",
    notes: "Vector DB practitioners = production AI builders.",
  },
  {
    slug: "wandb",
    name: "Weights & Biases events",
    tier: 2,
    baseScore: 76,
    url: "https://wandb.ai/site/events",
    sourceType: "web",
    notes: "ML practitioners, often senior. Production-focused.",
  },
  {
    slug: "fireworks-ai",
    name: "Fireworks AI events",
    tier: 2,
    baseScore: 78,
    url: "https://fireworks.ai/blog",
    sourceType: "web",
    notes: "Inference infra company. Hires the archetype.",
  },
  {
    slug: "groq",
    name: "Groq events",
    tier: 2,
    baseScore: 76,
    url: "https://groq.com/events/",
    sourceType: "web",
    notes: "Hardware-AI crossover. Senior infra practitioners.",
  },
  {
    slug: "vercel-ai",
    name: "Vercel AI events",
    tier: 2,
    baseScore: 74,
    url: "https://vercel.com/events",
    sourceType: "web",
    notes: "Often co-hosted with framework partners. Front-end-heavy AI builders.",
  },

  // ───────── Tier 3: Individual high-leverage hosts ─────────
  // No real calendars; tracked here so they appear in the registry,
  // and to remind us to add their events to manual-events.json when heard.
  {
    slug: "elad-gil",
    name: "Elad Gil (operator dinners)",
    tier: 3,
    baseScore: 92,
    url: "https://blog.eladgil.com/",
    sourceType: "web",
    notes: "High-leverage operator dinners. Rarely public; track via Twitter + warm intros.",
  },
  {
    slug: "garry-tan",
    name: "Garry Tan (YC President)",
    tier: 3,
    baseScore: 88,
    url: "https://www.garrytan.com/",
    sourceType: "web",
    notes: "YC-affiliated dinners + public talks. Strong access to YC alumni.",
  },
  {
    slug: "aaron-levie",
    name: "Aaron Levie (Box CEO)",
    tier: 3,
    baseScore: 80,
    url: "https://twitter.com/levie",
    sourceType: "web",
    notes: "Hosts AI exec dinners. Track via Twitter; rarely on public calendars.",
  },
  {
    slug: "aravind-srinivas",
    name: "Aravind Srinivas (Perplexity)",
    tier: 3,
    baseScore: 82,
    url: "https://aravsrinivas.com/",
    sourceType: "web",
    notes: "Hosts occasional talks + dinners. Brings Perplexity team + adjacent AI staff.",
  },
  {
    slug: "brett-adcock",
    name: "Brett Adcock (Figure)",
    tier: 3,
    baseScore: 78,
    url: "https://twitter.com/adcock_brett",
    sourceType: "web",
    notes: "Embodied AI founder community.",
  },

  // ───────── Tier 4: Hackathon orgs ─────────
  {
    slug: "encode-club",
    name: "Encode Club",
    tier: 4,
    baseScore: 70,
    url: "https://www.encode.club/",
    sourceType: "web",
    notes: "Web3/AI hackathons. Technical density.",
  },
  {
    slug: "lablab-ai",
    name: "Lablab.ai",
    tier: 4,
    baseScore: 70,
    url: "https://lablab.ai/event",
    sourceType: "web",
    notes: "AI hackathon platform. Often runs SF events.",
  },
  {
    slug: "founders-live",
    name: "Founders Live SF",
    tier: 4,
    baseScore: 72,
    url: "https://founderslive.com/sanfrancisco",
    sourceType: "web",
    notes: "Pitch night format. Surfaces between-things founders.",
  },

  // ───────── Aggregators (lower precision, higher recall) ─────────
  {
    slug: "luma-sf-discover",
    name: "Lu.ma SF discover (catch-all)",
    tier: 2,
    baseScore: 60,
    url: "https://lu.ma/sf",
    sourceType: "luma",
    notes: "Catches events from hosts we don't track. Lower archetype density, wider net.",
  },
  {
    slug: "eventbrite-sf-ai",
    name: "Eventbrite SF AI events",
    tier: 2,
    baseScore: 55,
    url: "https://www.eventbrite.com/d/ca--san-francisco/ai/",
    sourceType: "web",
    notes: "Lower-quality but catches enterprise events.",
  },
];

export function getHost(slug: string): Host | undefined {
  return HOSTS.find((h) => h.slug === slug);
}

export const HOSTS_BY_SLUG = new Map(HOSTS.map((h) => [h.slug, h]));
